/**
 * The one place that knows how the opaque session identifier travels: inside an
 * **HttpOnly** cookie (`FR-090`).
 *
 * The cookie name is server-side knowledge only. It is HttpOnly, so client-side
 * JavaScript never reads it (that is the point); the frontend never needs to
 * know its name, only that the browser stores and sends it automatically.
 *
 * ## Why a hand-written cookie reader instead of `cookie-parser`
 *
 * The API intentionally has no cookie-parsing dependency. The session identifier
 * is a 64-hex string generated by the service, so the only value this parser
 * must ever understand is `[a-f0-9]{64}` -- no percent-encoding, no quoted
 * values, no expiry attributes. The reader below is deliberately tiny and
 * fail-closed: an unreadable header yields `undefined`, which the authentication
 * middleware treats as "no credentials". The `cookie` package is already a
 * transitive dependency of Express, but relying on a transitive dependency from
 * application code is exactly the kind of implicit contract the project avoids.
 *
 * ## Cookie attributes (FR-090, OQ-025)
 *
 * `HttpOnly` (not readable by JS), `SameSite=Lax` (a real control but never the
 * sole CSRF defence -- the synchronizer-token check is separate and mandatory),
 * `Path=/`, and `Secure` only in production. Local development runs over HTTP on
 * `localhost`, where a `Secure` cookie would never be stored by the browser at
 * all; TLS termination is the deployment-time setting that flips this on.
 */
import type { Request, Response } from 'express';

import { SESSION_LIFETIME_MS } from '../services/session.service.js';

/** The cookie carrying the opaque session identifier. */
export const SESSION_COOKIE_NAME = 'hf_session';

/**
 * Read a single cookie by name from a `Cookie` request header.
 *
 * Returns `undefined` for a missing header, a missing name, or a malformed
 * segment. Defensively unwraps one level of double quotes, which some clients
 * add; no percent-decoding is performed because the only value this API ever
 * puts in the cookie is 64 lowercase hex characters.
 */
function readCookie(header: string | undefined, name: string): string | undefined {
  if (header === undefined) {
    return undefined;
  }

  for (const segment of header.split(';')) {
    const equals = segment.indexOf('=');
    if (equals === -1) {
      continue;
    }
    if (segment.slice(0, equals).trim() === name) {
      return segment.slice(equals + 1).trim().replace(/^"(.*)"$/, '$1');
    }
  }

  return undefined;
}

/** The session identifier presented for this request, or undefined. */
export function readSessionIdentifier(req: Request): string | undefined {
  return readCookie(req.headers.cookie, SESSION_COOKIE_NAME);
}

/**
 * The attributes every session cookie must carry (`FR-090`, `OQ-025`).
 *
 * `maxAge` is a browser-side hint matching the server-side absolute lifetime;
 * it is never the security boundary -- the server re-checks `expiresAt` and the
 * idle timeout on every request.
 */
export function sessionCookieOptions(secure: boolean): {
  readonly httpOnly: true;
  readonly secure: boolean;
  readonly sameSite: 'lax';
  readonly path: '/';
  readonly maxAge: number;
} {
  return {
    httpOnly: true,
    secure,
    sameSite: 'lax',
    path: '/',
    maxAge: SESSION_LIFETIME_MS,
  };
}

/** Remove the session cookie from the browser (logout). */
export function clearSessionCookie(res: Response): void {
  res.clearCookie(SESSION_COOKIE_NAME, { path: '/' });
}